# Generated by Django 3.0.3 on 2020-02-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mocar1',
            name='edad',
            field=models.IntegerField(),
        ),
    ]
