# Generated by Django 3.0.3 on 2020-04-01 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Login', '0002_auto_20200213_1351'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mocar1',
        ),
    ]
